### PR TITLE
Make plate steps and eco feedback available in device status

### PR DESCRIPTION
**Pull request by slootjes**
Noticed my Miele@home app can show the current state of my cooktop while this info wasn't available in HA yet. I've checked the API response, noticed the data is indeed present and made it available in the device status.

Also, could the "hacktoberfest" topic be added to the repository?

### CODE REVIEW

**Comment by kloknibor** [comment]
Sorry for the late reply, appearantly don't get notifications from this project yet. your PR seems ok so merging. Thanks for your input!

**Comment by kloknibor** [comment]
Also what do you mean with the hacktoberfest topic?

**Comment by slootjes** [comment]
Thanks for merging. The topic was for https://hacktoberfest.digitalocean.com/ so nevermind at this point.

**Comment by kloknibor** [comment]
sorry about that!

**Comment by slootjes** [comment]
No worries, thanks for merging!

**Pull request merged**
